export const GET_TOP_TRACKS = "GET_TOP_TRACKS";
export const GET_TRACK_LYRICS = "GET_TRACK_LYRICS";
export const GET_TRACK_DETAILS = "GET_TRACK_DETAILS";
export const SEARCH_TRACKES = "SEARCH_TRACKES";
